# Base configs
title: molly arhammar - portfolio
email: mollyarhammar@gmail.com
description: >
  If Hermione wrote Java. {I code stuff and design stuff and like
  communication and integration and kind people. Look at my things.}
url: https://theuggla.github.io
author: Molly Arhammar
share_image: share.png
background_image: default_rustic.jpg
rss: true

# Usernames
disqus_shortname: mollyarhammar
github_username: theuggla
youtube_channel: UC1SUarN21dtTZ4VudH39Ycg
skype_inviteURL: eUUh6HLdOlp4
linkedin_usernameURL: molly-arhammar


# Jekyll build settings
markdown: kramdown
theme: lysande
permalink: pretty
baseurl: ""
exclude: 
   - Gemfile
   - Gemfile.lock
   - lysande.gemspec
   - README.md

# Collections
collections:
  projects:
    categories: [code, design, published]

# Defaults
defaults:
  -
     scope:
        path: ""
     values:
        layout: "default"
  -
     scope:
        path: ""
        type: "posts"
     values:
        layout: "post"


