# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: molly arhammar - portfolio
email: mollyarhammar@gmail.com
description: >
  If Hermione wrote Java. {I code stuff and design stuff and like
  communication and integration and kind people. Look at my things.}
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Molly Arhammar
image: defaultprofile.png
rss: true

#usernames
disqus_shortname: mollyarhammar
twitter_username: theuggla
github_username: theuggla
tumblr_username: theuggla
instagram_username: mollyarhammar
facebook_username: molly.arhammar

# Build settings
markdown: kramdown
theme: lysande

# Collections
collections:
  projects:
    categories: [code, design, publish]

# Defaults
defaults:
  -
     scope:
        path: ""
     values:
        layout: "default"
  -
     scope:
        path: ""
        type: "posts"
     values:
        layout: "post"


