title: molly arhammar - portfolio
email: mollyarhammar@gmail.com
description: >
  If Hermione wrote Java. {I code stuff and design stuff and like
  communication and integration and kind people. Look at my things.}
baseurl: ""
url: ""
author: Molly Arhammar
image: share.png
rss: true

#usernames
disqus_shortname: mollyarhammar
twitter_username: theuggla
github_username: theuggla
tumblr_username: theuggla
instagram_username: mollyarhammar
facebook_username: molly.arhammar

# Build settings
markdown: kramdown
theme: lysande

# Collections
collections:
  projects:
    categories: [code, design, publish]

# Defaults
defaults:
  -
     scope:
        path: ""
     values:
        layout: "default"
  -
     scope:
        path: ""
        type: "posts"
     values:
        layout: "post"


